import { EntradaBlog } from '../../nucleo/dominio/blog.model';

export const entradasBlog: EntradaBlog[] = [
  {
    id: 1,
    titulo: 'Bienestar integrativo: primeros pasos',
    slug: 'bienestar-integrativo-primeros-pasos',
    resumen: 'Una introducción práctica para empezar a cuidar hábitos, descanso y equilibrio cotidiano.',
    contenido: ['Contenido completo pendiente de edición.'],
    categoria: 'Bienestar',
    imagen: 'tarjetas/bienestar-holistico.png',
    fecha: '01 JUN 2026',
    fechaPublicacion: '2026-06-01',
    visitas: '0',
    autor: 'Anonimo',
    publicada: true,
    etiquetas: ['bienestar', 'autocuidado', 'salud natural'],
  },
  {
    id: 2,
    titulo: 'Iridología como herramienta complementaria',
    slug: 'iridologia-como-herramienta-complementaria',
    resumen: 'Una introducción práctica para empezar a cuidar hábitos, descanso y equilibrio cotidiano.',
    contenido: ['Contenido completo pendiente de edición.'],
    categoria: 'Iridología',
    imagen: 'tarjetas/iris-test.png',
    fecha: '01 JUN 2026',
    fechaPublicacion: '2026-06-01',
    visitas: '0',
    autor: 'Anonimo',
    publicada: true,
    etiquetas: ['iridología', 'observación', 'bienestar'],
  },
  {
    id: 3,
    titulo: 'Reflexología y relajación corporal',
    slug: 'reflexologia-y-relajacion-corporal',
    resumen: 'Cómo las técnicas manuales suaves pueden apoyar momentos de calma y conciencia corporal.',
    contenido: ['Contenido completo pendiente de edición.'],
    categoria: 'Terapias',
    imagen: 'tarjetas/reflexo-test.png',
    fecha: '01 JUN 2026',
    fechaPublicacion: '2026-06-01',
    visitas: '0',
    autor: 'Anonimo',
    publicada: true,
    etiquetas: ['reflexología', 'relajación', 'cuerpo'],
  },
];